// A list of professional icons for skills.
// The 'tags' array is used for the search functionality.
export const icons = [
    { name: 'JavaScript', class: 'fab fa-js-square', tags: ['web', 'programming', 'language'] },
    { name: 'React', class: 'fab fa-react', tags: ['web', 'frontend', 'library', 'js'] },
    { name: 'Node.js', class: 'fab fa-node-js', tags: ['backend', 'server', 'js'] },
    { name: 'Python', class: 'fab fa-python', tags: ['programming', 'backend', 'data'] },
    { name: 'Java', class: 'fab fa-java', tags: ['programming', 'backend', 'enterprise'] },
    { name: 'HTML5', class: 'fab fa-html5', tags: ['web', 'frontend', 'markup'] },
    { name: 'CSS3', class: 'fab fa-css3-alt', tags: ['web', 'frontend', 'style'] },
    { name: 'Sass', class: 'fab fa-sass', tags: ['css', 'style', 'preprocessor'] },
    { name: 'Figma', class: 'fab fa-figma', tags: ['design', 'ui', 'ux', 'prototype'] },
    { name: 'Database', class: 'fas fa-database', tags: ['sql', 'backend', 'data', 'storage'] },
    { name: 'Git', class: 'fab fa-git-alt', tags: ['version control', 'code'] },
    { name: 'GitHub', class: 'fab fa-github', tags: ['version control', 'code', 'hosting'] },
    { name: 'Docker', class: 'fab fa-docker', tags: ['devops', 'container', 'server'] },
    { name: 'AWS', class: 'fab fa-aws', tags: ['cloud', 'hosting', 'server', 'devops'] },
    { name: 'Palette', class: 'fas fa-palette', tags: ['design', 'art', 'ui', 'ux', 'color'] },
    { name: 'Comments', class: 'fas fa-comments', tags: ['communication', 'soft skill', 'speaking'] },
    { name: 'Users', class: 'fas fa-users', tags: ['teamwork', 'collaboration', 'soft skill'] },
    { name: 'Chart', class: 'fas fa-chart-line', tags: ['data', 'analytics', 'business'] },
    { name: 'Code', class: 'fas fa-code', tags: ['programming', 'development'] },
    { name: 'Server', class: 'fas fa-server', tags: ['backend', 'hosting', 'devops'] },
    { name: 'Brain', class: 'fas fa-brain', tags: ['ai', 'machine learning', 'data science'] },
    { name: 'Mobile', class: 'fas fa-mobile-alt', tags: ['app', 'android', 'ios'] },
    { name: 'Bug', class: 'fas fa-bug', tags: ['testing', 'debug', 'qa'] },
    { name: 'Terminal', class: 'fas fa-terminal', tags: ['cli', 'devops', 'sysadmin'] },
    { name: 'Cloud', class: 'fas fa-cloud', tags: ['cloud', 'hosting', 'devops'] },
    { name: 'Shield', class: 'fas fa-shield-alt', tags: ['security', 'cybersecurity', 'protection'] },
    { name: 'Cog', class: 'fas fa-cog', tags: ['configuration', 'settings', 'systems'] },
    { name: 'Rocket', class: 'fas fa-rocket', tags: ['startup', 'launch', 'fast'] },
    { name: 'Lightbulb', class: 'fas fa-lightbulb', tags: ['ideas', 'innovation', 'creative'] },
    { name: 'Wrench', class: 'fas fa-wrench', tags: ['tools', 'repair', 'maintenance'] },
];
